from dataclasses import dataclass, field


@dataclass
class Recommendation:
    """
    Represents a journal recommendation generated by the ranking engine.

    A Recommendation is not the journal itself.
    It is the result of evaluating a journal against a specific manuscript
    and recommendation strategy.
    """

    # Journal Information
    journal_name: str
    publisher: str
    indexing: str
    journal_rank: str
    language: str
    submission_url: str

    # Publication Cost
    apc_display: str          # e.g. "Free", "$150", "Unknown"
    apc_value: float | None   # Numeric value used for ranking/filtering

    # Scores
    recommendation_score: float
    match_score: float

    # Recommendation Context
    strategy: str = "Balanced"

    # Explainable Recommendation
    reasons: list[str] = field(default_factory=list)